- hosts: localhost
  gather_facts: yes 
  sudo: no

  tasks:

    - include: roles/common/tasks/base.yml

    - include: roles/common/tasks/languages.yml

    - include: roles/common/tasks/browsers.yml

    - include: roles/common/task/editors.yml


    - name: Install postgres
      homebrew: name=postgresql state=present

    - name: Install coreutils
      homebrew:  name=coreutils state=present

    - name: Install mongodb
      homebrew: name=mongodb state=present

    - name: Install cassandra
      homebrew: name=cassandra state=present

    - name: Install neo4j
      homebrew: name=neo4j state=present

    - name: Install node
      homebrew: name=node state=present

    - name: Install nginx
      homebrew: name=nginx state=present

