- hosts: localhost
  gather_facts: yes 
  sudo: no

  tasks:

    - include: roles/common/tasks/base.yml

    - include: roles/common/tasks/languages.yml

    - include: roles/common/tasks/browsers.yml

    - name: Install macvim
      homebrew: name=macvim state=present

    - name: Install sublime
      homebrew_cask: name=sublime-text state=present

    - name: Install textmate
      homebrew_cask: name=textmate state=present

    - name: Install emacs
      homebrew_cask: name=emacs state=present

    - name: Install postgres
      homebrew: name=postgresql state=present

    - name: Install coreutils
      homebrew:  name=coreutils state=present

    - name: Install mongodb
      homebrew: name=mongodb state=present

    - name: Install cassandra
      homebrew: name=cassandra state=present

    - name: Install neo4j
      homebrew: name=neo4j state=present

    - name: Install node
      homebrew: name=node state=present

    - name: Install nginx
      homebrew: name=nginx state=present

