- hosts: localhost
  gather_facts: yes 
  sudo: no

  tasks:

    - include: roles/common/tasks/base.yml

    - include: roles/common/tasks/languages.yml

    - include: roles/common/tasks/browsers.yml

    - include: roles/common/tasks/editors.yml

    - include: roles/common/tasks/databases.yml

    - name: Install coreutils
      homebrew:  name=coreutils state=present


    - name: Install node
      homebrew: name=node state=present

    - name: Install nginx
      homebrew: name=nginx state=present

