- name: Update Homebrew
  command: brew update

- name: Setup Homebrew Dupes
  homebrew_tap: tap=homebrew/dupes state=present

- name: Setup Homebrew Casks
  homebrew_tap: tap=caskroom/cask state=present

- name: Setup Homebrew Cask Versions
  homebrew_tap: tap=caskroom/versions state=present

- name: Install Brew Cask
  homebrew: name=brew-cask state=latest

- name: Install coreutils
  homebrew:  name=coreutils state=latest

- name: Install iterm2
  homebrew_cask: name=iterm2 state=present

- name: Install git
  homebrew: name=git state=latest

# These libs may be needed to build nokogiri

- name: Install libxml2
  homebrew: name=libxml2 state=latest

- name: Install libxslt
  homebrew: name=libxslt state=latest

- name: Install libiconv
  homebrew: name=libiconv state=latest

- name: Install apple-gcc42
  homebrew: name=apple-gcc42 state=latest

- name: Install ACK
  homebrew: name=ack state=latest

# End nokogiri libs

- name: Install electric-sheep
  homebrew_cask: name=electric-sheep state=present

