- name: Install Homebrew
  shell: roles/files/install_homebrew.sh >> /tmp/hombrew_install_out.txt creates=/usr/local/Cellar

- name: Update Homebrew
  command: brew update

- name: Setup Homebrew Dupes
  homebrew_tap: tap=homebrew/dupes state=present

- name: Setup Homebrew Casks
  homebrew_tap: tap=caskroom/cask state=present

- name: Install Brew Cask
  homebrew: name=brew-cask state=present

- name: Install coreutils
  homebrew:  name=coreutils state=present

# These libs may be needed to build nokogiri

- name: Install libxml2
  homebrew: name=libxml2 state=present

- name: Install libxslt
  homebrew: name=libxslt state=present

- name: Install libiconv
  homebrew: name=libiconv state=present

- name: Install apple-gcc42
  homebrew: name=apple-gcc42 state=present

# End nokogiri libs
