- name: Install postgres
  homebrew: name=postgresql state=present

- name: Install mongodb
  homebrew: name=mongodb state=present

- name: Install cassandra
  homebrew: name=cassandra state=present

- name: Install neo4j
  homebrew: name=neo4j state=present
