- name: Install macvim
  homebrew: name=macvim state=latest

- name: Add wildignores to vimrc.after
  lineinfile: dest=~/.vimrc.after line="set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/public/paperclip/*" create=yes
  sudo: no

- name: Add whitespace helpers to vimrc.after (depends on janus)
  lineinfile: dest=~/.vimrc.after line="nnoremap <F2>     :FixWhitespace<CR>\nautocmd BufWritePre * :Fix" create=yes
  sudo: no

- name: Install sublime
  homebrew_cask: name=sublime-text state=present

- name: Install textmate
  homebrew_cask: name=textmate state=present

- name: Install emacs
  homebrew_cask: name=emacs state=present

- name: Install gimp
  homebrew_cask: name=gimp state=present

- name: Install atom
  homebrew_cask: name=atom state=present

- name: Install ctags
  homebrew: name=ctags state=latest
