- name: Install Java
  homebrew_cask: name=java state=present

- debug: msg="If your Java application still asks for JRE installation, you might need to reboot or logout/login. Run `brew cask info java` on the command line for more info."

- name: Install Python
  homebrew: name=python state=present

- name: Install Scala
  homebrew: name=scala state=present

- name: Install Rbenv
  homebrew: name=rbenv state=present

- name: Add rbenv init to bash_profile
  lineinfile: dest=~/.bash_profile line='eval "$(rbenv init -)"'

- name: Install ruby-build
  homebrew: name=ruby-build state=present

- name: Install ruby 2.1.2
  command: rbenv install 2.1.2 creates=~/.rbenv/versions/2.1.2

- name: Install ruby 2.1.0
  command: rbenv install 2.1.0 creates=~/.rbenv/versions/2.1.0

- name: Install ruby 1.9.3
  command: rbenv install 1.9.3-p545 creates=~/.rbenv/versions/1.9.3-p545

- name: Install node
  homebrew: name=node state=present

- name: Install erlang
  homebrew: name=erlang state=present
