- name: Install Java
  homebrew_cask: name=java state=present

- name: Install Java7 # required by Neo4J
  homebrew_cask: name=java7 state=present

- debug: msg="If your Java application still asks for JRE installation, you might need to reboot or logout/login. Run `brew cask info java` on the command line for more info."

- name: Install Python
  homebrew: name=python state=latest

- name: Install Scala
  homebrew: name=scala state=latest

- name: Install Rbenv
  homebrew: name=rbenv state=latest

- name: Add rbenv init to bash_profile
  lineinfile: dest=~/.bash_profile line='eval "$(rbenv init -)"'

- name: Install ruby-build
  homebrew: name=ruby-build state=latest

- name: Install ruby 2.1.5
  command: rbenv install 2.1.5 creates=~/.rbenv/versions/2.1.5

- name: Install ruby 2.1.4
  command: rbenv install 2.1.4 creates=~/.rbenv/versions/2.1.4

- name: Install ruby 2.1.3
  command: rbenv install 2.1.3 creates=~/.rbenv/versions/2.1.3

- name: Install ruby 2.1.2
  command: rbenv install 2.1.2 creates=~/.rbenv/versions/2.1.2

- name: Install ruby 2.1.1
  command: rbenv install 2.1.1 creates=~/.rbenv/versions/2.1.1

- name: Install ruby 2.1.0
  command: rbenv install 2.1.0 creates=~/.rbenv/versions/2.1.0

- name: Install ruby 1.9.3
  command: rbenv install 1.9.3-p545 creates=~/.rbenv/versions/1.9.3-p545

- name: Install jruby 1.7.9
  command: rbenv install jruby-1.7.9 creates=~/.rbenv/versions/jruby-1.7.9

- name: Install jruby 1.7.16.1
  command: rbenv install jruby-1.7.16.1 creates=~/.rbenv/versions/jruby-1.7.16.1

- name: Set global ruby version 
  copy: src=version dest=~/.ruby-version mode="0644"

- name: Install the current rails gem
  gem: name=rails state=latest

- name: Install the current bundler gem
  gem: name=bundler state=latest

- name: Install node
  homebrew: name=node state=latest

- name: Install erlang
  homebrew: name=erlang state=present

