- name: Install arq
  homebrew_cask: name=arq state=present

- name: Install grandperspective
  homebrew_cask: name=grandperspective state=present

- name: Install utorrent
  homebrew_cask: name=utorrent state=present
