- name: Install virtualbox
  homebrew_cask: name=virtualbox state=present

- name: Install vagrant
  homebrew_cask: name=vagrant state=present

- name: Install s3cmd
  homebrew: name=s3cmd state=latest

- name: Install Docker
  homebrew_cask: name=boot2docker state=present

- name: Install Fig 
  homebrew: name=fig state=present

- name: Set docker and fig enviroment variables
  lineinfile: dest=~/.bashrc line="$(boot2docker shellinit)"
  sudo: no

